BanksySan.Demo.Web.Mvc.Authentication/Models/CustomPrincipalSerializeModel.cs
namespace BanksySan.Demo.Web.Mvc.Authentication.Models
{
    using System.Collections.Generic;

    public class CustomPrincipalSerializeModel
    {
        public string UserName { get; set; }
        public IEnumerable<string> Roles { get; set; }
    }
}

BanksySan.Demo.Web.Mvc.Authentication/Models/HomeModel.cs
namespace BanksySan.Demo.Web.Mvc.Authentication.Models
{
    using System.Collections.Generic;
    using DataStore;

    public class HomeModel
    {
        public IEnumerable<User> Users { get; set; }

        public IEnumerable<Role> Roles { get; set; }
    }
}

BanksySan.Demo.Web.Mvc.Authentication/Models/LogInViewModel.cs
namespace BanksySan.Demo.Web.Mvc.Authentication.Models
{
    using System.ComponentModel.DataAnnotations;

    public class LoginViewModel
    {
        [Required]
        [Display(Name = "User name")]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }
}

BanksySan.Demo.Web.Mvc.Authentication/Models/LoggedInModel.cs
namespace BanksySan.Demo.Web.Mvc.Authentication.Models
{
    using System.Collections.Generic;

    public class LoggedInModel
    {
        public string UserName { get; set; }

        public IEnumerable<string> Roles { get; set; }
    }
}

BanksySan.Demo.Web.Mvc.Authentication/Controllers/AdministratorOnlyController.cs
namespace BanksySan.Demo.Web.Mvc.Authentication.Controllers
{
    using System.Web.Mvc;
    using Authentication;

    [CustomAuthorize(Roles = "Administrator")]
    public class AdministratorOnlyController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

BanksySan.Demo.Web.Mvc.Authentication/Controllers/AuthenticationController.cs
namespace BanksySan.Demo.Web.Mvc.Authentication.Controllers
{
    using System;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using System.Web.Security;
    using DataStore;
    using Models;
    using Newtonsoft.Json;

    public class AuthenticationController : Controller
    {
        private readonly FakeDataStore _dataStore = new FakeDataStore();

        [HttpPost]
        public ActionResult LogIn(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user =
                    _dataStore.Users
                        .FirstOrDefault(u => u.UserName == model.Username && u.Password == model.Password);

                if (user != null)
                {
                    var roleNames = user.Roles.Select(role => role.Name).ToArray();

                    var serializeModel = new CustomPrincipalSerializeModel
                    {
                        UserName = user.UserName,
                        Roles = roleNames
                    };

                    var userData = JsonConvert.SerializeObject(serializeModel);
                    var issueDate = DateTime.Now;

                    var authenticationTicket = new FormsAuthenticationTicket(1,
                        user.UserName,
                        issueDate,
                        issueDate.AddMinutes(5),
                        false,
                        userData);

                    var encryptedTicket = FormsAuthentication.Encrypt(authenticationTicket);
                    var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    Response.AppendCookie(cookie);

                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Error", model);
        }

        public ActionResult Error(string message)
        {
            TempData["message"] = message;
            return View();
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

BanksySan.Demo.Web.Mvc.Authentication/Controllers/HomeController.cs
namespace BanksySan.Demo.Web.Mvc.Authentication.Controllers
{
    using System;
    using System.Web.Mvc;
    using System.Web.Security;
    using DataStore;
    using Models;

    public class HomeController : Controller
    {
        private static readonly FakeDataStore DATA_STORE = new FakeDataStore();

        public ActionResult Index(bool expireCookie = false)
        {
            if (expireCookie)
            {
                FormsAuthentication.SignOut();
                //var cookie = Request.Cookies[FormsAuthentication.FormsCookieName];

                //if (cookie != null)
                //{
                //    cookie.Expires = DateTime.Now.AddMinutes(-1);
                //}
            }

            var homeModel = new HomeModel
            {
                Roles = DATA_STORE.Roles,
                Users = DATA_STORE.Users
            };
            return View(homeModel);
        }
    }
}

BanksySan.Demo.Web.Mvc.Authentication/Views/AdministratorOnly/Index.cshtml
<html>
<body>
<p>You are in the Administrator Area</p>

<p>@Html.ActionLink("Return to home", "Index", "Home")</p>
</body>
</html>

BanksySan.Demo.Web.Mvc.Authentication/Views/Home/Index.cshtml
@model BanksySan.Demo.Web.Mvc.Authentication.Models.HomeModel

<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    <p>Users:</p>
    <div>
        <b>Users: </b>
        @foreach (var user in Model.Users)
        {
            <div style="border: blue solid thick; float: left;">
                <p>User: @user.UserName</p>
                <p>Password: @user.Password</p>
                <p>Roles: @string.Join(", ", user.Roles.Select(x => x.Name))</p>
            </div>
        }
    </div>

    <div style="clear: both">
        <p>Roles:</p>
        @foreach (var role in Model.Roles)
        {
            <div style="border: blue solid thick; float: left;">
                <p>Name: @role.Name</p>
                <p>Users: @string.Join(", ", role.Users.Select(x => x.UserName))</p>
            </div>
        }
    </div>

    <div style="float: left; clear: both">
        Navigate: <ul>
            <li>@Html.ActionLink("Administrator only", "Index", "AdministratorOnly")</li>
            <li>@Html.ActionLink("User only", "Index", "UserOnly")</li>
        </ul>
    </div>

    <div>
        @Html.ActionLink("Expire authentication cookie", "Index", new { ExpireCookie = true })
    </div>

    @using (@Html.BeginForm("LogIn", "Authentication", FormMethod.Post, new { style = "clear: both" }))
    {
        <label for="username">User name: </label>
        <input type="text" name="username" id="username"/>
        <label for="password">Password</label>
        <input type="text" name="password" id="password"/>
        <input type="submit" value="Submit"/>
    }
</div>
</body>
</html>

BanksySan.Demo.Web.Mvc.Authentication/Views/UserOnly/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>title</title>
</head>
<body>
<div>
    <p>User only view</p>
    <p>@Html.ActionLink("Return to home", "Index", "Home")</p>
</div>
</body>
</html>